### ISSUE TITLE
#1 Code Review session

### ISSUE THREAD

**Issue by ptahdunbar** [Shonte/shontedeveaux.com#1]
- [x] Learn [Git](https://try.github.io/)
- [x] Confirm SSH keys are uploaded to github
- [x] Fill out GitHub account details including (name, bio, url, company, location, and available for hire)
- [x] Upload code to Github
- [x] Sign up to [bitbucket](https://bitbucket.org/) and leave a comment with your username

Next steps
- QA website code and set milestones for applying any fixes and improvements

**Comment by Shonte** [comment]
https://bitbucket.org/Shonte/
